version: '3.9'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mohamed123
      POSTGRES_DB: MENAH
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    environment:
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASS: mohamed123
      DB_NAME: MENAH
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  pgdata:
